/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/$workspaceSlug/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as WorkspaceSlugSettingsIndexRouteImport } from './routes/$workspaceSlug/settings/index'
import { Route as ApiPlatformWorkspacesRouteImport } from './routes/api/platform/workspaces'
import { Route as ApiPlatformWorkspaceRouteImport } from './routes/api/platform/workspace'
import { Route as ApiPlatformSessionRouteImport } from './routes/api/platform/session'
import { Route as ApiPlatformRunsRouteImport } from './routes/api/platform/runs'
import { Route as ApiPlatformInvitesRouteImport } from './routes/api/platform/invites'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiGithubInstallRouteImport } from './routes/api/github/install'
import { Route as WorkspaceSlugSettingsRepositoriesRouteImport } from './routes/$workspaceSlug/settings/repositories'
import { Route as WorkspaceSlugSettingsMembersRouteImport } from './routes/$workspaceSlug/settings/members'
import { Route as WorkspaceSlugSettingsGithubRouteImport } from './routes/$workspaceSlug/settings/github'
import { Route as ApiPlatformRepositoriesSelectionRouteImport } from './routes/api/platform/repositories/selection'
import { Route as ApiPlatformRepositoriesBranchRouteImport } from './routes/api/platform/repositories/branch'
import { Route as ApiGithubInstallCallbackRouteImport } from './routes/api/github/install/callback'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/$workspaceSlug/',
  path: '/$workspaceSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugSettingsIndexRoute =
  WorkspaceSlugSettingsIndexRouteImport.update({
    id: '/$workspaceSlug/settings/',
    path: '/$workspaceSlug/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlatformWorkspacesRoute = ApiPlatformWorkspacesRouteImport.update({
  id: '/api/platform/workspaces',
  path: '/api/platform/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformWorkspaceRoute = ApiPlatformWorkspaceRouteImport.update({
  id: '/api/platform/workspace',
  path: '/api/platform/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformSessionRoute = ApiPlatformSessionRouteImport.update({
  id: '/api/platform/session',
  path: '/api/platform/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformRunsRoute = ApiPlatformRunsRouteImport.update({
  id: '/api/platform/runs',
  path: '/api/platform/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlatformInvitesRoute = ApiPlatformInvitesRouteImport.update({
  id: '/api/platform/invites',
  path: '/api/platform/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubInstallRoute = ApiGithubInstallRouteImport.update({
  id: '/api/github/install',
  path: '/api/github/install',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugSettingsRepositoriesRoute =
  WorkspaceSlugSettingsRepositoriesRouteImport.update({
    id: '/$workspaceSlug/settings/repositories',
    path: '/$workspaceSlug/settings/repositories',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugSettingsMembersRoute =
  WorkspaceSlugSettingsMembersRouteImport.update({
    id: '/$workspaceSlug/settings/members',
    path: '/$workspaceSlug/settings/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugSettingsGithubRoute =
  WorkspaceSlugSettingsGithubRouteImport.update({
    id: '/$workspaceSlug/settings/github',
    path: '/$workspaceSlug/settings/github',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlatformRepositoriesSelectionRoute =
  ApiPlatformRepositoriesSelectionRouteImport.update({
    id: '/api/platform/repositories/selection',
    path: '/api/platform/repositories/selection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlatformRepositoriesBranchRoute =
  ApiPlatformRepositoriesBranchRouteImport.update({
    id: '/api/platform/repositories/branch',
    path: '/api/platform/repositories/branch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGithubInstallCallbackRoute =
  ApiGithubInstallCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiGithubInstallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/settings/github': typeof WorkspaceSlugSettingsGithubRoute
  '/$workspaceSlug/settings/members': typeof WorkspaceSlugSettingsMembersRoute
  '/$workspaceSlug/settings/repositories': typeof WorkspaceSlugSettingsRepositoriesRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/platform/invites': typeof ApiPlatformInvitesRoute
  '/api/platform/runs': typeof ApiPlatformRunsRoute
  '/api/platform/session': typeof ApiPlatformSessionRoute
  '/api/platform/workspace': typeof ApiPlatformWorkspaceRoute
  '/api/platform/workspaces': typeof ApiPlatformWorkspacesRoute
  '/$workspaceSlug/settings/': typeof WorkspaceSlugSettingsIndexRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/platform/repositories/branch': typeof ApiPlatformRepositoriesBranchRoute
  '/api/platform/repositories/selection': typeof ApiPlatformRepositoriesSelectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$workspaceSlug': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/settings/github': typeof WorkspaceSlugSettingsGithubRoute
  '/$workspaceSlug/settings/members': typeof WorkspaceSlugSettingsMembersRoute
  '/$workspaceSlug/settings/repositories': typeof WorkspaceSlugSettingsRepositoriesRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/platform/invites': typeof ApiPlatformInvitesRoute
  '/api/platform/runs': typeof ApiPlatformRunsRoute
  '/api/platform/session': typeof ApiPlatformSessionRoute
  '/api/platform/workspace': typeof ApiPlatformWorkspaceRoute
  '/api/platform/workspaces': typeof ApiPlatformWorkspacesRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsIndexRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/platform/repositories/branch': typeof ApiPlatformRepositoriesBranchRoute
  '/api/platform/repositories/selection': typeof ApiPlatformRepositoriesSelectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/settings/github': typeof WorkspaceSlugSettingsGithubRoute
  '/$workspaceSlug/settings/members': typeof WorkspaceSlugSettingsMembersRoute
  '/$workspaceSlug/settings/repositories': typeof WorkspaceSlugSettingsRepositoriesRoute
  '/api/github/install': typeof ApiGithubInstallRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/platform/invites': typeof ApiPlatformInvitesRoute
  '/api/platform/runs': typeof ApiPlatformRunsRoute
  '/api/platform/session': typeof ApiPlatformSessionRoute
  '/api/platform/workspace': typeof ApiPlatformWorkspaceRoute
  '/api/platform/workspaces': typeof ApiPlatformWorkspacesRoute
  '/$workspaceSlug/settings/': typeof WorkspaceSlugSettingsIndexRoute
  '/api/github/install/callback': typeof ApiGithubInstallCallbackRoute
  '/api/platform/repositories/branch': typeof ApiPlatformRepositoriesBranchRoute
  '/api/platform/repositories/selection': typeof ApiPlatformRepositoriesSelectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/api/inngest'
    | '/auth/callback'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/settings/github'
    | '/$workspaceSlug/settings/members'
    | '/$workspaceSlug/settings/repositories'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/platform/invites'
    | '/api/platform/runs'
    | '/api/platform/session'
    | '/api/platform/workspace'
    | '/api/platform/workspaces'
    | '/$workspaceSlug/settings/'
    | '/api/github/install/callback'
    | '/api/platform/repositories/branch'
    | '/api/platform/repositories/selection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/api/inngest'
    | '/auth/callback'
    | '/$workspaceSlug'
    | '/$workspaceSlug/settings/github'
    | '/$workspaceSlug/settings/members'
    | '/$workspaceSlug/settings/repositories'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/platform/invites'
    | '/api/platform/runs'
    | '/api/platform/session'
    | '/api/platform/workspace'
    | '/api/platform/workspaces'
    | '/$workspaceSlug/settings'
    | '/api/github/install/callback'
    | '/api/platform/repositories/branch'
    | '/api/platform/repositories/selection'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/onboarding'
    | '/api/inngest'
    | '/auth/callback'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/settings/github'
    | '/$workspaceSlug/settings/members'
    | '/$workspaceSlug/settings/repositories'
    | '/api/github/install'
    | '/api/github/webhook'
    | '/api/platform/invites'
    | '/api/platform/runs'
    | '/api/platform/session'
    | '/api/platform/workspace'
    | '/api/platform/workspaces'
    | '/$workspaceSlug/settings/'
    | '/api/github/install/callback'
    | '/api/platform/repositories/branch'
    | '/api/platform/repositories/selection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiInngestRoute: typeof ApiInngestRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugSettingsGithubRoute: typeof WorkspaceSlugSettingsGithubRoute
  WorkspaceSlugSettingsMembersRoute: typeof WorkspaceSlugSettingsMembersRoute
  WorkspaceSlugSettingsRepositoriesRoute: typeof WorkspaceSlugSettingsRepositoriesRoute
  ApiGithubInstallRoute: typeof ApiGithubInstallRouteWithChildren
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiPlatformInvitesRoute: typeof ApiPlatformInvitesRoute
  ApiPlatformRunsRoute: typeof ApiPlatformRunsRoute
  ApiPlatformSessionRoute: typeof ApiPlatformSessionRoute
  ApiPlatformWorkspaceRoute: typeof ApiPlatformWorkspaceRoute
  ApiPlatformWorkspacesRoute: typeof ApiPlatformWorkspacesRoute
  WorkspaceSlugSettingsIndexRoute: typeof WorkspaceSlugSettingsIndexRoute
  ApiPlatformRepositoriesBranchRoute: typeof ApiPlatformRepositoriesBranchRoute
  ApiPlatformRepositoriesSelectionRoute: typeof ApiPlatformRepositoriesSelectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/': {
      id: '/$workspaceSlug/'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings/': {
      id: '/$workspaceSlug/settings/'
      path: '/$workspaceSlug/settings'
      fullPath: '/$workspaceSlug/settings/'
      preLoaderRoute: typeof WorkspaceSlugSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/workspaces': {
      id: '/api/platform/workspaces'
      path: '/api/platform/workspaces'
      fullPath: '/api/platform/workspaces'
      preLoaderRoute: typeof ApiPlatformWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/workspace': {
      id: '/api/platform/workspace'
      path: '/api/platform/workspace'
      fullPath: '/api/platform/workspace'
      preLoaderRoute: typeof ApiPlatformWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/session': {
      id: '/api/platform/session'
      path: '/api/platform/session'
      fullPath: '/api/platform/session'
      preLoaderRoute: typeof ApiPlatformSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/runs': {
      id: '/api/platform/runs'
      path: '/api/platform/runs'
      fullPath: '/api/platform/runs'
      preLoaderRoute: typeof ApiPlatformRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/invites': {
      id: '/api/platform/invites'
      path: '/api/platform/invites'
      fullPath: '/api/platform/invites'
      preLoaderRoute: typeof ApiPlatformInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install': {
      id: '/api/github/install'
      path: '/api/github/install'
      fullPath: '/api/github/install'
      preLoaderRoute: typeof ApiGithubInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings/repositories': {
      id: '/$workspaceSlug/settings/repositories'
      path: '/$workspaceSlug/settings/repositories'
      fullPath: '/$workspaceSlug/settings/repositories'
      preLoaderRoute: typeof WorkspaceSlugSettingsRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings/members': {
      id: '/$workspaceSlug/settings/members'
      path: '/$workspaceSlug/settings/members'
      fullPath: '/$workspaceSlug/settings/members'
      preLoaderRoute: typeof WorkspaceSlugSettingsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings/github': {
      id: '/$workspaceSlug/settings/github'
      path: '/$workspaceSlug/settings/github'
      fullPath: '/$workspaceSlug/settings/github'
      preLoaderRoute: typeof WorkspaceSlugSettingsGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/repositories/selection': {
      id: '/api/platform/repositories/selection'
      path: '/api/platform/repositories/selection'
      fullPath: '/api/platform/repositories/selection'
      preLoaderRoute: typeof ApiPlatformRepositoriesSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/platform/repositories/branch': {
      id: '/api/platform/repositories/branch'
      path: '/api/platform/repositories/branch'
      fullPath: '/api/platform/repositories/branch'
      preLoaderRoute: typeof ApiPlatformRepositoriesBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/install/callback': {
      id: '/api/github/install/callback'
      path: '/callback'
      fullPath: '/api/github/install/callback'
      preLoaderRoute: typeof ApiGithubInstallCallbackRouteImport
      parentRoute: typeof ApiGithubInstallRoute
    }
  }
}

interface ApiGithubInstallRouteChildren {
  ApiGithubInstallCallbackRoute: typeof ApiGithubInstallCallbackRoute
}

const ApiGithubInstallRouteChildren: ApiGithubInstallRouteChildren = {
  ApiGithubInstallCallbackRoute: ApiGithubInstallCallbackRoute,
}

const ApiGithubInstallRouteWithChildren =
  ApiGithubInstallRoute._addFileChildren(ApiGithubInstallRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  ApiInngestRoute: ApiInngestRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugSettingsGithubRoute: WorkspaceSlugSettingsGithubRoute,
  WorkspaceSlugSettingsMembersRoute: WorkspaceSlugSettingsMembersRoute,
  WorkspaceSlugSettingsRepositoriesRoute:
    WorkspaceSlugSettingsRepositoriesRoute,
  ApiGithubInstallRoute: ApiGithubInstallRouteWithChildren,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiPlatformInvitesRoute: ApiPlatformInvitesRoute,
  ApiPlatformRunsRoute: ApiPlatformRunsRoute,
  ApiPlatformSessionRoute: ApiPlatformSessionRoute,
  ApiPlatformWorkspaceRoute: ApiPlatformWorkspaceRoute,
  ApiPlatformWorkspacesRoute: ApiPlatformWorkspacesRoute,
  WorkspaceSlugSettingsIndexRoute: WorkspaceSlugSettingsIndexRoute,
  ApiPlatformRepositoriesBranchRoute: ApiPlatformRepositoriesBranchRoute,
  ApiPlatformRepositoriesSelectionRoute: ApiPlatformRepositoriesSelectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
